# name of Docker container
container_image = docker://jaronthompson/nsm_dependencies:v1
universe = container

log = job_$(Cluster)_$(Process).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = run_CDanc.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = glove_L1.tar.gz, folds_CDanc.tar.gz, CDanc_20fold.py

request_cpus = 1
request_memory = 4GB
request_disk = 4GB

queue 2000
